#-------------------------------
# General Site Settings

title: Afnan Mostafa
description: personal portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://afnanmostafa.github.io" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Afnan Mostafa
#author-avatar: 09.jpg


#-------------------------------
# Contact links
#facebook:  https://www.facebook.com/itsafnan/ # Add your Facebook handle
#twitter:   https://twitter.com/ # Add your Facebook handle
instagram: https://www.instagram.com/afnan_most/ # Add your Facebook handle
#pinterest: https://www.pinterest.com/ # Add your Facebook handle
LinkedIn: https://www.linkedin.com/in/afnan-mostafa
GitHub: https://github.com/afnanmostafa
GoogleScholar: https://scholar.google.com/citations?user=oFWNZhsAAAAJ&hl=en
ResearchGate: https://www.researchgate.net/profile/Afnan_Mostafa

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
